apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aks-sync-cert-manager-certs-on-key-vault.fullname" . }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.env.AZURE_CLIENT_ID | quote }}
  labels:
    azure.workload.identity/use: "true"